name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11
      - name: 'Setup Node.js with pnpm cache'
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - run: pnpm install --frozen-lockfile
      - run: pnpm run format
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test:ci

      - name: Setup git coordinates
        run: |
          git config user.name uport-automation-bot
          git config user.email devops@veramo.io

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release
